#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

sv start gearman || exit 1

echo "Starting gcron ..."
exec /gcron --v=4
