// Code generated by "stringer -type=PT ../../pkg/runtime/protocol.go"; DO NOT EDIT

package runtime

import "fmt"

const (
	_PT_name_0 = "PT_CanDoPT_CantDoPT_ResetAbilitiesPT_PreSleep"
	_PT_name_1 = "PT_NoopPT_SubmitJobPT_JobCreatedPT_GrabJobPT_NoJobPT_JobAssignPT_WorkStatusPT_WorkCompletePT_WorkFailPT_GetStatusPT_EchoReqPT_EchoResPT_SubmitJobBGPT_ErrorPT_StatusResPT_SubmitJobHighPT_SetClientIdPT_CanDoTimeoutPT_AllYoursPT_WorkExceptionPT_OptionReqPT_OptionResPT_WorkDataPT_WorkWarningPT_GrabJobUniqPT_JobAssignUniqPT_SubmitJobHighBGPT_SubmitJobLowPT_SubmitJobLowBGPT_SubmitJobSchedPT_SubmitJobEpochPT_SubmitReduceJobPT_SubmitReduceJobBackgroundPT_GrabJobAllPT_JobAssignAllPT_GetStatusUniquePT_StatusResUnique"
)

var (
	_PT_index_0 = [...]uint8{0, 8, 17, 34, 45}
	_PT_index_1 = [...]uint16{0, 7, 19, 32, 42, 50, 62, 75, 90, 101, 113, 123, 133, 147, 155, 167, 183, 197, 212, 223, 239, 251, 263, 274, 288, 302, 318, 336, 351, 368, 385, 402, 420, 448, 461, 476, 494, 512}
)

func (i PT) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _PT_name_0[_PT_index_0[i]:_PT_index_0[i+1]]
	case 6 <= i && i <= 42:
		i -= 6
		return _PT_name_1[_PT_index_1[i]:_PT_index_1[i+1]]
	default:
		return fmt.Sprintf("PT(%d)", i)
	}
}
